# https://github.com/robvanderleek/create-issue-branch#option-2-configure-github-action
mode: auto
silent: false
branchName: "${issue.number}-${issue.title,}"
autoCloseIssue: true
gitSafeReplacementChar: "-"
branches:
  - label: feature
    prefix: feature/
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
  - label: documentation
    prefix: docs/
  - label: '*'
    prefix: issues/