disabled_rules:
#- trailing_whitespace
- large_tuple
- function_parameter_count
- force_cast

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
- SmartColony/R.generated.swift

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    
function_body_length:
    warning: 300
    error: 500
    
function_parameter_count:
    warning: 6
    error: 8
    
type_body_length:
    warning: 300
    error: 500
    
file_length:
    warning: 2000
    error: 2500
    ignore_comment_only_lines: true
    
cyclomatic_complexity:
    warning: 51
    error: 75
    
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
    allowed_symbols: "_"
    min_length: 4 # only warning
    max_length: # warning and error
        warning: 40
        error: 50
    excluded: 
    - UI
    
identifier_name:
    allowed_symbols: "_"
    min_length: # only min_length
        error: 3 # only error
    excluded: # excluded via string array
    - x
    - y
    - pt
    - id
    - dx
    - dy
    - to
    - nx
    - ny
    - on
    
reporter: "xcode"