//
//  DiplomaticRequestState.swift
//  SmartAILibrary
//
//  Created by Michael Rommel on 09.06.20.
//  Copyright © 2020 Michael Rommel. All rights reserved.
//

import Foundation

public enum DiplomaticRequestState: Int, Codable {

    case intro // DIPLO_UI_STATE_DEFAULT_ROOT

    case warDeclaredByHuman // DIPLO_UI_STATE_WAR_DECLARED_BY_HUMAN
    case peaceMadeByHuman // DIPLO_UI_STATE_PEACE_MADE_BY_HUMAN

    case blankDiscussion // DIPLO_UI_STATE_BLANK_DISCUSSION

    case trade // DIPLO_UI_STATE_TRADE
    case tradeAIMakesOffer // DIPLO_UI_STATE_TRADE_AI_MAKES_OFFER,

    case discussHumanInvoked // DIPLO_UI_STATE_DISCUSS_HUMAN_INVOKED

    /*DIPLO_UI_STATE_TRADE_AI_ACCEPTS_OFFER,
    DIPLO_UI_STATE_TRADE_AI_REJECTS_OFFER,
    DIPLO_UI_STATE_TRADE_AI_MAKES_DEMAND,
    DIPLO_UI_STATE_TRADE_AI_MAKES_REQUEST,
    DIPLO_UI_STATE_TRADE_HUMAN_OFFERS_CONCESSIONS,

    DIPLO_UI_STATE_HUMAN_DEMAND,

    DIPLO_UI_STATE_BLANK_DISCUSSION_RETURN_TO_ROOT,
    ,
    DIPLO_UI_STATE_BLANK_DISCUSSION_MEAN_HUMAN,
    DIPLO_UI_STATE_BLANK_DISCUSSION_MEAN_AI,
    DIPLO_UI_STATE_AI_DECLARED_WAR,

    DIPLO_UI_STATE_DISCUSS_HUMAN_INVOKED,

    DIPLO_UI_STATE_DISCUSS_AGGRESSIVE_MILITARY_WARNING,
    DIPLO_UI_STATE_DISCUSS_I_ATTACKED_YOUR_MINOR_CIV,
    DIPLO_UI_STATE_DISCUSS_I_BULLIED_YOUR_MINOR_CIV,
    DIPLO_UI_STATE_DISCUSS_YOU_ATTACKED_MINOR_CIV,
    DIPLO_UI_STATE_DISCUSS_YOU_KILLED_MINOR_CIV,
    DIPLO_UI_STATE_DISCUSS_YOU_BULLIED_MINOR_CIV,
    DIPLO_UI_STATE_DISCUSS_PROTECT_MINOR_CIV,
    DIPLO_UI_STATE_DISCUSS_YOU_EXPANSION_SERIOUS_WARNING,
    DIPLO_UI_STATE_DISCUSS_YOU_EXPANSION_WARNING,
    DIPLO_UI_STATE_DISCUSS_YOU_PLOT_BUYING_SERIOUS_WARNING,
    DIPLO_UI_STATE_DISCUSS_YOU_PLOT_BUYING_WARNING,

    DIPLO_UI_STATE_DISCUSS_WORK_WITH_US,
    DIPLO_UI_STATE_DISCUSS_WORK_AGAINST_SOMEONE,*/
    case discussCoopWar // DIPLO_UI_STATE_DISCUSS_COOP_WAR,
    case discussCoopWarTime // DIPLO_UI_STATE_DISCUSS_COOP_WAR_TIME,

    /*DIPLO_UI_STATE_DISCUSS_PLAN_RESEARCH_AGREEMENT,

    // Post Civ 5 release stuff
    DIPLO_UI_STATE_DISCUSS_AI_REQUEST_DENOUNCE,

    // Espionage
    DIPLO_UI_STATE_CAUGHT_YOUR_SPY,
    DIPLO_UI_STATE_KILLED_YOUR_SPY,
    DIPLO_UI_STATE_KILLED_MY_SPY,
    DIPLO_UI_STATE_CONFRONT_YOU_KILLED_MY_SPY,

    DIPLO_UI_STATE_STOP_CONVERSIONS,

    DIPLO_UI_STATE_STOP_DIGGING,
    */
}
