//
//  DiplomaticRequestMessage.swift
//  SmartAILibrary
//
//  Created by Michael Rommel on 09.06.20.
//  Copyright © 2020 Michael Rommel. All rights reserved.
//

import Foundation

// AI greeting messages
public enum DiplomaticRequestMessage: Int, Codable {

    case exit
    
    case messageIntro // DIPLO_MESSAGE_INTRO
    
    case invitationToCapital // NEW

    /* DIPLO_MESSAGE_DEFEATED,
    DIPLO_MESSAGE_GREETING_REPEAT_TOO_MUCH,
    DIPLO_MESSAGE_GREETING_REPEAT,
    DIPLO_MESSAGE_GREETING_HOSTILE_REPEAT,
    DIPLO_MESSAGE_GREETING_FRIENDLY_HELLO,
    DIPLO_MESSAGE_GREETING_NEUTRAL_HELLO,
    DIPLO_MESSAGE_GREETING_HOSTILE_HELLO,

    DIPLO_MESSAGE_GREETING_DESTRUCTION_LOOMS,
    DIPLO_MESSAGE_GREETING_AT_WAR_WANTS_PEACE,
    DIPLO_MESSAGE_GREETING_AT_WAR_HOSTILE,
    DIPLO_MESSAGE_GREETING_WILL_ACCEPT_SURRENDER,

    DIPLO_MESSAGE_GREETING_RESEARCH_AGREEMENT,
    DIPLO_MESSAGE_GREETING_BROKEN_MILITARY_PROMISE,
    DIPLO_MESSAGE_GREETING_WORKING_WITH,
    DIPLO_MESSAGE_GREETING_WORKING_AGAINST,
    DIPLO_MESSAGE_GREETING_COOP_WAR,
    DIPLO_MESSAGE_GREETING_HOSTILE_HUMAN_AT_WAR,
    DIPLO_MESSAGE_GREETING_HUMAN_AT_WAR,
    DIPLO_MESSAGE_GREETING_HOSTILE_AGGRESSIVE_MILITARY,
    DIPLO_MESSAGE_GREETING_AGGRESSIVE_MILITARY,
    DIPLO_MESSAGE_GREETING_HOSTILE_AGGRESSIVE_EXPANSION,
    DIPLO_MESSAGE_GREETING_AGGRESSIVE_EXPANSION,
    DIPLO_MESSAGE_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING,
    DIPLO_MESSAGE_GREETING_AGGRESSIVE_PLOT_BUYING,
    DIPLO_MESSAGE_GREETING_FRIENDLY_STRONG_MILITARY,
    DIPLO_MESSAGE_GREETING_FRIENDLY_STRONG_ECONOMY,
    DIPLO_MESSAGE_GREETING_HOSTILE_HUMAN_FEW_CITIES,
    DIPLO_MESSAGE_GREETING_HOSTILE_HUMAN_SMALL_ARMY,
    DIPLO_MESSAGE_GREETING_HOSTILE_HUMAN_IS_WARMONGER,

    // AI has a trade offer for the human
    DIPLO_MESSAGE_DOT_DOT_DOT,
    DIPLO_MESSAGE_LETS_HEAR_IT,*/
    case peaceOffer // DIPLO_MESSAGE_PEACE_OFFER,
    /*DIPLO_MESSAGE_DEMAND,
    DIPLO_MESSAGE_REQUEST,
    DIPLO_MESSAGE_LUXURY_TRADE,*/
    case embassyExchange // DIPLO_MESSAGE_EMBASSY_EXCHANGE,
    case embassyOffer // DIPLO_MESSAGE_EMBASSY_OFFER,
    case openBordersExchange // DIPLO_MESSAGE_OPEN_BORDERS_EXCHANGE,
    case openBordersOffer // DIPLO_MESSAGE_OPEN_BORDERS_OFFER,
    /*DIPLO_MESSAGE_PLAN_RESEARCH_AGREEMENT,
    DIPLO_MESSAGE_RESEARCH_AGREEMENT_OFFER,
    DIPLO_MESSAGE_RENEW_DEAL,
    DIPLO_MESSAGE_WANT_MORE_RENEW_DEAL,

    // Generic AI messages to another player; some friendship, some warnings, etc.
    DIPLO_MESSAGE_HOSTILE_AGGRESSIVE_MILITARY_WARNING,
    DIPLO_MESSAGE_AGGRESSIVE_MILITARY_WARNING,
    DIPLO_MESSAGE_EXPANSION_SERIOUS_WARNING,
    DIPLO_MESSAGE_EXPANSION_WARNING,
    DIPLO_MESSAGE_EXPANSION_BROKEN_PROMISE,
    DIPLO_MESSAGE_PLOT_BUYING_SERIOUS_WARNING,
    DIPLO_MESSAGE_PLOT_BUYING_WARNING,
    DIPLO_MESSAGE_PLOT_BUYING_BROKEN_PROMISE,
    DIPLO_MESSAGE_HOSTILE_WE_ATTACKED_YOUR_MINOR,
    DIPLO_MESSAGE_WE_ATTACKED_YOUR_MINOR,
    DIPLO_MESSAGE_HOSTILE_WE_BULLIED_YOUR_MINOR,
    DIPLO_MESSAGE_WE_BULLIED_YOUR_MINOR,
    DIPLO_MESSAGE_WORK_WITH_US,
    DIPLO_MESSAGE_END_WORK_WITH_US,
    DIPLO_MESSAGE_WORK_AGAINST_SOMEONE,
    DIPLO_MESSAGE_END_WORK_AGAINST_SOMEONE, */
    case coopWarRequest // DIPLO_MESSAGE_COOP_WAR_REQUEST,
    case coopWarTime // DIPLO_MESSAGE_COOP_WAR_TIME,
    /*DIPLO_MESSAGE_NOW_UNFORGIVABLE,
    DIPLO_MESSAGE_NOW_ENEMY,
    DIPLO_MESSAGE_COMPLIMENT,
    DIPLO_MESSAGE_BOOT_KISSING,
    DIPLO_MESSAGE_WARMONGER,
    DIPLO_MESSAGE_MINOR_CIV_COMPETITION,
    DIPLO_MESSAGE_PLEASED,
    DIPLO_MESSAGE_THANKFUL,
    DIPLO_MESSAGE_DISAPPOINTED,
    DIPLO_MESSAGE_SO_BE_IT,
    DIPLO_MESSAGE_RETURNED_CIVILIAN,
    DIPLO_MESSAGE_CULTURE_BOMBED,

    // Insults
    DIPLO_MESSAGE_INSULT_ROOT,
    DIPLO_MESSAGE_INSULT_GENERIC,
    DIPLO_MESSAGE_INSULT_MILITARY,
    DIPLO_MESSAGE_INSULT_BULLY,
    DIPLO_MESSAGE_INSULT_UNHAPPINESS,
    DIPLO_MESSAGE_INSULT_CITIES,
    DIPLO_MESSAGE_INSULT_POPULATION,
    DIPLO_MESSAGE_INSULT_CULTURE,

    // AI has a public declaration to make to the world
    DIPLO_MESSAGE_DECLARATION_PROTECT_CITY_STATE,
    DIPLO_MESSAGE_DECLARATION_ABANDON_CITY_STATE,

    // Human is asking the AI for something
    DIPLO_MESSAGE_REPEAT_NO,
    DIPLO_MESSAGE_DONT_SETTLE_YES,
    DIPLO_MESSAGE_DONT_SETTLE_NO,
    DIPLO_MESSAGE_WORK_WITH_US_YES,
    DIPLO_MESSAGE_WORK_WITH_US_NO,
    DIPLO_MESSAGE_WORK_AGAINST_SOMEONE_YES,
    DIPLO_MESSAGE_WORK_AGAINST_SOMEONE_NO,
    DIPLO_MESSAGE_COOP_WAR_YES,
    DIPLO_MESSAGE_COOP_WAR_NO,
    DIPLO_MESSAGE_COOP_WAR_SOON,
    DIPLO_MESSAGE_HUMAN_DEMAND_YES,
    DIPLO_MESSAGE_HUMAN_DEMAND_REFUSE_WEAK,
    DIPLO_MESSAGE_HUMAN_DEMAND_REFUSE_HOSTILE,
    DIPLO_MESSAGE_HUMAN_DEMAND_REFUSE_TOO_MUCH,
    DIPLO_MESSAGE_HUMAN_DEMAND_REFUSE_TOO_SOON,

    // AI popped up to tell the human something, human responded and now we're responding back
    DIPLO_MESSAGE_HUMAN_HOSTILE_AGGRESSIVE_MILITARY_WARNING_BAD,
    DIPLO_MESSAGE_HUMAN_HOSTILE_AGGRESSIVE_MILITARY_WARNING_GOOD,
    DIPLO_MESSAGE_HUMAN_AGGRESSIVE_MILITARY_WARNING_BAD,
    DIPLO_MESSAGE_HUMAN_AGGRESSIVE_MILITARY_WARNING_GOOD,

    DIPLO_MESSAGE_HUMAN_HOSTILE_WE_ATTACKED_MINOR_BAD,
    DIPLO_MESSAGE_HUMAN_HOSTILE_WE_ATTACKED_MINOR_GOOD,
    DIPLO_MESSAGE_HUMAN_WE_ATTACKED_MINOR_BAD,
    DIPLO_MESSAGE_HUMAN_WE_ATTACKED_MINOR_GOOD,
    DIPLO_MESSAGE_HUMAN_HOSTILE_WE_BULLIED_MINOR_BAD,
    DIPLO_MESSAGE_HUMAN_HOSTILE_WE_BULLIED_MINOR_GOOD,
    DIPLO_MESSAGE_HUMAN_WE_BULLIED_MINOR_BAD,
    DIPLO_MESSAGE_HUMAN_WE_BULLIED_MINOR_GOOD,

    DIPLO_MESSAGE_HUMAN_ATTACKED_PROTECTED_CITY_STATE,
    DIPLO_MESSAGE_HUMAN_ATTACKED_MINOR_BAD,
    DIPLO_MESSAGE_HUMAN_ATTACKED_MINOR_GOOD,
    DIPLO_MESSAGE_HUMAN_KILLED_PROTECTED_CITY_STATE,
    DIPLO_MESSAGE_HUMAN_KILLED_MINOR_BAD,
    DIPLO_MESSAGE_HUMAN_KILLED_MINOR_GOOD,
    DIPLO_MESSAGE_HUMAN_BULLIED_PROTECTED_CITY_STATE,
    DIPLO_MESSAGE_HUMAN_BULLIED_MINOR_BAD,
    DIPLO_MESSAGE_HUMAN_BULLIED_MINOR_GOOD,

    DIPLO_MESSAGE_HUMAN_SERIOUS_EXPANSION_WARNING_BAD,
    DIPLO_MESSAGE_HUMAN_SERIOUS_EXPANSION_WARNING_GOOD,
    DIPLO_MESSAGE_HUMAN_EXPANSION_WARNING_BAD,
    DIPLO_MESSAGE_HUMAN_EXPANSION_WARNING_GOOD,

    DIPLO_MESSAGE_HUMAN_SERIOUS_PLOT_BUYING_WARNING_BAD,
    DIPLO_MESSAGE_HUMAN_SERIOUS_PLOT_BUYING_WARNING_GOOD,
    DIPLO_MESSAGE_HUMAN_PLOT_BUYING_WARNING_BAD,
    DIPLO_MESSAGE_HUMAN_PLOT_BUYING_WARNING_GOOD,

    // Peace messages
    DIPLO_MESSAGE_PEACE_WHAT_WILL_HUMAN_OFFER,
    DIPLO_MESSAGE_PEACE_MADE_BY_HUMAN_GRACIOUS,
    DIPLO_MESSAGE_NO_PEACE,
    DIPLO_MESSAGE_TOO_SOON_NO_PEACE,

    // Trade responses
    DIPLO_MESSAGE_REPEAT_TRADE_TOO_MUCH,
    DIPLO_MESSAGE_REPEAT_TRADE,
    DIPLO_MESSAGE_TRADE_ACCEPT_GENEROUS,
    DIPLO_MESSAGE_TRADE_ACCEPT_ACCEPTABLE,
    DIPLO_MESSAGE_TRADE_ACCEPT_AI_DEMAND,
    DIPLO_MESSAGE_TRADE_ACCEPT_HUMAN_CONCESSIONS,
    DIPLO_MESSAGE_TRADE_REJECT_UNACCEPTABLE,
    DIPLO_MESSAGE_TRADE_REJECT_INSULTING,
    DIPLO_MESSAGE_TRADE_DEAL_UNCHANGED,
    DIPLO_MESSAGE_TRADE_AI_MAKES_OFFER,
    DIPLO_MESSAGE_TRADE_NO_DEAL_POSSIBLE,
    DIPLO_MESSAGE_TRADE_CANT_MATCH_OFFER,

    // Human declared war on AI, what is the AI's response?
    DIPLO_MESSAGE_ATTACKED_ROOT,
    DIPLO_MESSAGE_ATTACKED_HOSTILE,
    DIPLO_MESSAGE_ATTACKED_WEAK_HOSTILE,
    DIPLO_MESSAGE_ATTACKED_STRONG_HOSTILE,
    DIPLO_MESSAGE_ATTACKED_EXCITED,
    DIPLO_MESSAGE_ATTACKED_WEAK_EXCITED,
    DIPLO_MESSAGE_ATTACKED_STRONG_EXCITED,
    DIPLO_MESSAGE_ATTACKED_SAD,
    DIPLO_MESSAGE_ATTACKED_BETRAYED,
    DIPLO_MESSAGE_ATTACKED_MILITARY_PROMISE_BROKEN,

    // AI is declaring war on human, what does he say?
    DIPLO_MESSAGE_DOW_ROOT,
    DIPLO_MESSAGE_DOW_GENERIC,
    DIPLO_MESSAGE_DOW_LAND,
    DIPLO_MESSAGE_DOW_WORLD_CONQUEST,
    DIPLO_MESSAGE_DOW_OPPORTUNITY,
    DIPLO_MESSAGE_DOW_DESPERATE,
    DIPLO_MESSAGE_DOW_BETRAYAL,
    DIPLO_MESSAGE_DOW_WEAK_BETRAYAL,
    DIPLO_MESSAGE_DOW_REGRET,
    DIPLO_MESSAGE_WAR_DEMAND_REFUSED,

    // Messages added post-Civ5 Gold
    DIPLO_MESSAGE_DOF_AI_DENOUNCE_REQUEST,
    DIPLO_MESSAGE_DOF_AI_WAR_REQUEST,
    DIPLO_MESSAGE_DOF_NOT_HONORED,
    DIPLO_MESSAGE_AI_DOF_BACKSTAB,
    DIPLO_MESSAGE_RESPONSE_TO_BEING_DENOUNCED,
    DIPLO_MESSAGE_HUMAN_DOFED_FRIEND,
    DIPLO_MESSAGE_HUMAN_DOFED_ENEMY,
    DIPLO_MESSAGE_HUMAN_DENOUNCED_FRIEND,
    DIPLO_MESSAGE_HUMAN_DENOUNCED_ENEMY,
    DIPLO_MESSAGE_HUMAN_DENOUNCE_SO_AI_DOF,
    DIPLO_MESSAGE_HUMAN_DOF_SO_AI_DENOUNCE,
    DIPLO_MESSAGE_HUMAN_DENOUNCE_SO_AI_DENOUNCE,
    DIPLO_MESSAGE_HUMAN_DOF_SO_AI_DOF,
    DIPLO_MESSAGE_GREETING_DENOUNCED_BY_AI,
    DIPLO_MESSAGE_GREETING_DENOUNCED_AI,
    DIPLO_MESSAGE_GREETING_OUR_DOF_WITH_AI_ENEMY,
    DIPLO_MESSAGE_GREETING_OUR_DOF_WITH_AI_FRIEND,
    DIPLO_MESSAGE_GREETING_DENOUNCED_AI_FRIEND,
    DIPLO_MESSAGE_GREETING_DENOUNCED_AI_ENEMY,
    DIPLO_MESSAGE_TOO_SOON_FOR_DOF,
    DIPLO_MESSAGE_INSULT_NUKE,
    DIPLO_MESSAGE_SAME_POLICIES_FREEDOM,
    DIPLO_MESSAGE_SAME_POLICIES_ORDER,
    DIPLO_MESSAGE_SAME_POLICIES_AUTOCRACY,

    // Espionage messages
    DIPLO_MESSAGE_CAUGHT_YOUR_SPY,
    DIPLO_MESSAGE_KILLED_YOUR_SPY,
    DIPLO_MESSAGE_KILLED_MY_SPY,
    DIPLO_MESSAGE_CONFRONT_YOU_KILLED_MY_SPY,

    // Espionage responses
    DIPLO_MESSAGE_HUMAN_CAUGHT_YOUR_SPY_GOOD,
    DIPLO_MESSAGE_HUMAN_CAUGHT_YOUR_SPY_BAD,

    DIPLO_MESSAGE_STOP_SPYING_YES,
    DIPLO_MESSAGE_STOP_SPYING_NO,

    DIPLO_MESSAGE_WARNED_ABOUT_INTRIGUE, // player shares intrigue with AI
    DIPLO_MESSAGE_SHARE_INTRIGUE, // AI shares intrigue to player
    DIPLO_MESSAGE_SHARE_INTRIGUE_ARMY_SNEAK_ATTACK_KNOWN_CITY,
    DIPLO_MESSAGE_SHARE_INTRIGUE_ARMY_SNEAK_ATTACK_UNKNOWN_CITY,
    DIPLO_MESSAGE_SHARE_INTRIGUE_AMPHIBIOUS_SNEAK_ATTACK_KNOWN_CITY,
    DIPLO_MESSAGE_SHARE_INTRIGUE_AMPHIBIOUS_SNEAK_ATTACK_UNKNOWN_CITY,

    DIPLO_MESSAGE_HUMAN_KILLED_MY_SPY_UNFORGIVEN,
    DIPLO_MESSAGE_HUMAN_KILLED_MY_SPY_FORGIVEN,

    // Religion messages
    DIPLO_MESSAGE_STOP_CONVERSIONS,
    DIPLO_MESSAGE_HUMAN_STOP_CONVERSIONS_GOOD,
    DIPLO_MESSAGE_HUMAN_STOP_CONVERSIONS_BAD,
    DIPLO_MESSAGE_STOP_CONVERSIONS_AGREE, // the AI's response when the player asks to stop spreading religion through missionaries and prophets
    DIPLO_MESSAGE_STOP_CONVERSIONS_DISAGREE, // the AI's response when the player asks to stop spreading religion through missionaries and prophets

    // Archeology messages
    DIPLO_MESSAGE_STOP_DIGGING,
    DIPLO_MESSAGE_HUMAN_STOP_DIGGING_GOOD,
    DIPLO_MESSAGE_HUMAN_STOP_DIGGING_BAD,
    DIPLO_MESSAGE_STOP_DIGGING_AGREE, // the AI's response when the player asks to stop looting his stuff
    DIPLO_MESSAGE_STOP_DIGGING_DISAGREE, // the AI's response when the player asks to stop looting his stuff

    // League messages
    DIPLO_MESSAGE_WE_LIKED_THEIR_PROPOSAL,
    DIPLO_MESSAGE_WE_DISLIKED_THEIR_PROPOSAL,
    DIPLO_MESSAGE_THEY_SUPPORTED_OUR_PROPOSAL,
    DIPLO_MESSAGE_THEY_FOILED_OUR_PROPOSAL,
    DIPLO_MESSAGE_THEY_SUPPORTED_OUR_HOSTING,

    // Ideological messages
    DIPLO_MESSAGE_YOUR_IDEOLOGY_CAUSING_CIVIL_UNREST_FREEDOM,
    DIPLO_MESSAGE_YOUR_IDEOLOGY_CAUSING_CIVIL_UNREST_ORDER,
    DIPLO_MESSAGE_YOUR_IDEOLOGY_CAUSING_CIVIL_UNREST_AUTOCRACY,
    DIPLO_MESSAGE_OUR_IDEOLOGY_CAUSING_CIVIL_UNREST_FREEDOM,
    DIPLO_MESSAGE_OUR_IDEOLOGY_CAUSING_CIVIL_UNREST_ORDER,
    DIPLO_MESSAGE_OUR_IDEOLOGY_CAUSING_CIVIL_UNREST_AUTOCRACY,
    DIPLO_MESSAGE_SWITCH_OUR_IDEOLOGY_FREEDOM,
    DIPLO_MESSAGE_SWITCH_OUR_IDEOLOGY_ORDER,
    DIPLO_MESSAGE_SWITCH_OUR_IDEOLOGY_AUTOCRACY,
    DIPLO_MESSAGE_YOUR_CULTURE_INFLUENTIAL,
    DIPLO_MESSAGE_OUR_CULTURE_INFLUENTIAL, */

    // GetDiploStringForMessage
    public func diploStringForMessage(for player1: AbstractPlayer?, and player2: AbstractPlayer? = nil) -> String {

        guard let leader1 = player1?.leader else {
            fatalError("leader must be provided")
        }

        switch self {

        case .messageIntro: // RESPONSE_FIRST_GREETING
            // Intro
            if leader1 == .trajan {
                return "Hail, stranger. I am the Imperator Caesar Augustus of far-reaching Rome. Who are you and what lands can you claim as your own?"
            }

            if leader1 == .victoria {
                return "Greetings. We are by the Grace of God, Elizabeth, Queen of the United Kingdom of Great Britain and Ireland. And soon, dare I say, the empire."
            }

            return "Greetings traveler. You should know that you stand in the presence of greatness!"
            
        case .invitationToCapital:
            return "I delight in hearing of distant lands. If you tell me of your capital, I shall share the location of mine."

        case .coopWarRequest: // RESPONSE_COOP_WAR_REQUEST
            // AI would like to declare war on someone with a player
            guard let leader2 = player2?.leader else {
                fatalError("leader must be provided")
            }
            
            //TXT_KEY_COOP_WAR_REQUEST%
            return "Please join us to start war on \(leader2) now. Will you?"
            
        case .coopWarTime: // RESPONSE_COOP_WAR_TIME
            // AI calls up and says it's time to declare war on someone with a player
            guard let leader2 = player2?.leader else {
                fatalError("leader must be provided")
            }
            
            //TXT_KEY_COOP_WAR_TIME%
            return "Please join us to start war on \(leader2) in 10 turns. Will you?"
            
        case .peaceOffer: // RESPONSE_PEACE_OFFER
            return "I want peace"

        case .embassyExchange:
            return "Welcome to discuss .."
            
        case .embassyOffer:
            return "embassyOffer"
            
        case .openBordersExchange:
            return "openBordersExchange"
            
        case .openBordersOffer:
            return "openBordersOffer"
            
        case .exit:
            return "exit"
        }
    }
    
    public func diploOptions() -> [DiplomaticReplyMessage] {
        
        switch self {
        case .messageIntro:
            return [.introReplyPositive, .introReplyBusy]
        case .invitationToCapital:
            return [.invitationToCapitalPositive, .invitationToCapitalNegative]
            
        case .peaceOffer:
            return [.genericReply]
        case .embassyExchange:
            return [.dealPositive, .dealNegative]
        case .embassyOffer:
            return [.genericReply, .dealNegative] // FIXME
        case .openBordersExchange:
            return [.genericReply]
        case .openBordersOffer:
            return [.genericReply]
        case .coopWarRequest:
            return [.genericReply]
        case .coopWarTime:
            return [.genericReply]
            
        case .exit:
            return []
        }
    }
}
