name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Verify
      run: pwd
    - name: Build & Test
      run: set -o pipefail && xcodebuild -workspace Colony.xcworkspace -scheme SmartColony -destination platform\=iOS\ Simulator,OS\=14.2,name\=iPhone\ 12 build test | xcpretty
