name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.2,name=iPhone X', 'platform=iOS Simulator,OS=14.2,name=iPhone 12']

    steps:
    - uses: actions/checkout@v2
    - name: Verify
      run: ls
    - name: Build & Test
      run: xcodebuild clean test -project SmartColony.xcodeproj -scheme SmartColony -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
    #  run: set -o pipefail && xcodebuild -workspace Colony.xcworkspace -scheme SmartColony -destination platform\=iOS\ Simulator,OS\=14.2,name\=iPhone\ 12 build test | xcpretty
